### ISSUE TITLE
Viewer

### ISSUE THREAD

**Issue by fieldhof** [bpetri/nativeLoad#2] opened 2015-10-12 13:33 UTC
The current viewer doesn't always show every phone. The logs on the phone are still correct. The viewer seems correct and it's probably the statistics_endpoint which is causing this problem. Find this problem and fix it.

**Comment by marcojansen** [comment] 2015-10-22 13:53
Seems fixed with new celix and config. Might've been that wrong ip values were used. Can't reproduce this problem anymore. If this still happens sometimes it might have something to do with multiple ip's on a phone (3g and wifi at same time) .

**Closed as completed by marcojansen** 2015-10-22 13:53 UTC
Labels: bug
